# Generated by Django 3.1.5 on 2021-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ended_manually',
            field=models.BooleanField(default=False),
        ),
    ]
